Makefile
TODO.md
src/conn.c
src/test.c

* Made the reconnect process synchronous, otherwise there could be issues when getting authentication failures during that process.
* Added a test that demonstrated the issue and passing with this change.

Fix reconnect logic

---

TODO.md
src/conn.c
src/gc.h
src/msg.c
src/msg.h
src/nats.c
src/natsp.h
src/sub.c
src/sub.h

* Add a "garbage collector" that is responsible for invoking an object's "free" callback. The advantage is to move the cost of freeing objects outside of the fast path.
* Subject, Reply and Payload are now allocated as a single memory block. This reduces the number of malloc/free calls.
* Introduced a "signal" timer in each subscription to reduce number of signals and contention. This may increase the risk of reaching the number of max pending messages,
though, so may need some teaking or make it an option.

Performance improvements

---

src/comsock.c
src/comsock.h
src/conn.c
src/natsp.h
src/util.c
test/list.txt
test/test.c

During a (re)connect, the client is sending the CONNECT and PING protocol and expect a PONG. However, when Verbose option is set, the server will send "+OK" after receiving the CONNECT protocol. The client now dequeues the two protocols in that scenario.
* In sendConnect(), expect "+OK" when Verbose is set
* Change natsSock_ReadLine() to handle possible multiple line in single call.
* Add tests
Fixes #13

Fix sendConnect() call when Verbose is set

---

src/conn.c
src/natsp.h
src/pub.c
test/test.c

Also ported some of the changes from GO client
- Pending buffer created before the doReconnect thread is started.
- Revisited the use of nc->err to limit it to report async errors.
- Publish and Flush will no longer fail if an async error occurs.
- Ensure flusher is not reseting nc->err on buffer flush success.
- Removed double pending msg accounting.
- Tests updated.

Fix Publish and Flush calls to not fail on async error (slow consumer)

---

examples/examples.h
examples/replier.c
examples/subscriber.c
src/nats.h
src/natsp.h
src/sub.c
test/test.c

Some of the new limits and counters introduced in 1.3 were defined
as int, which would cause overflow when the number of messages was
high. Changed types to int64_t.

Fix unexpected drop of messages by subscribers

---

src/unix/mutex.c

The current spinlock code uses the "rep" instruction, which is not
supported on the ARM architecture.

Disable spinlock when building on ARM.

---

src/comsock.c
test/list.txt
test/test.c

We were trying IPv6 addresses but would not try IPv4 if we
got IPv6 addresses but could not connect, for instance because
the server was accepting connections on IPv4 address only.

[FIXED] Connect to server listening to IPv4 if host resolves to IPv6

---

src/err.h
src/include/n-unix.h
src/include/n-win.h

gcc5 complains about __FUNCTION__.

Use ISO __func__ instead of __FUNCTION__

---

src/srvpool.c
test/test.c

When connecting to a server, the received INFO may contain an array
of URLs. The current code was adding those and then shuffeling the
entire pool (if NoRandomize is false). This is wrong since the
connect (and reconnect) loop would then potentially skip never
tried servers and try again servers that had just failed.

[FIXED] Do not shuffle entire pool when adding URL from INFO

---

CMakeLists.txt
buildOnTravis.sh
src/nats.c
test/dylib/CMakeLists.txt
test/dylib/nonats.c

Specific to Windows (since it was previously fixed for other platforms).
This happens only when linking against the dynamic library and if
no call to NATS is made. Calling explicitly nats_Open()/nats_Close()
would prevent this crash from happening.
Resolves #54

[FIXED] Crash if linked to dynamic NATS lib no NATS API call is made

---

src/nats.c

Happens when application keeps reconnecting (e.g. maxReconnect=-1) and  errTL->func is filled with "natsConnection_FlushTimeout"/"natsConnection_Flush" sequences.

[FIXED] Crash in _updateStack (index out of range)

---

src/conn.c

This is in relation to PR #56 that fixed the crash when error stack
grows too big. The issue was discovered due to Flush() call failures
that repeated a number of times would make the error stack grow.

[FIXED] Prevent error stack growth when Flush()/FlushTimeout fails

---

README.md

I kept having to scroll around to find the docs link, usually it's at the very top. It may save some people a little time.

State the documentation link near the top of the readme [skip ci]

---

CMakeLists.txt
src/CMakeLists.txt
src/natstime.c

I was working on loading cnats via the ffi gem with jruby and noticed that I was having issues loading libnats because...
```
libnats.so: undefined symbol: clock_gettime.
```
This loads just fine under MRI.
I noticed we set the `NATS_EXTRA_LIB` var in the main `CMakeLists.txt` and that we use it for tests, but we we're not using it in `src/CMakeLists.txt`. Adding it back fixes the problem.
Here's a failing job in travis: https://travis-ci.org/abrandoned/protobuf-nats/jobs/218995507#L761

Add missing librt on linux via NATS_EXTRA_LIB var

---

src/conn.c
src/conn.h
src/nats.c
src/natsp.h
src/sub.c

When a client sends data and has at least a matching subscriber,
there may be a case where the flusher is holding the connection's
lock while trying to flush the write buffer, which cannot complete
because the server is not draining data at the moment since it is
itself trying to send data to the client, which processMsg() function
is waiting on the connection's lock. After 2 seconds, the server
will close the client connection.
Using a dedicated lock for the subscriptions map that processMsg
needs to access is reducing the risk of lock contention between
publish/flusher and the readloop's processMsg function.
There would still be a case where if the subscription in the client
is considered a slow consumer and messages are dropped, we need to
acquire the connection lock there. But in …

Reduce risk of server closing conn (slow consumer) if sending to itself

---

src/conn.c
src/natsp.h
test/list.txt
test/permissions.conf
test/test.c

If the application publishes or subscribes to a subject for which
the user does not have proper permissions, the client library
receives an error from the server. This needs to be handled properly
otherwise the connection ends-up being closed.
The library will now invoke the error handler if one is set.

[FIXED] Permissions violation handling

---

CMakeLists.txt
src/CMakeLists.txt
src/deprnats.h
src/version.h.in

When doing `make install`, the header files are now copied under
the `$CMAKE_INSTALL_PREFIX/include/nats`.
Resolves #72

[CHANGED] Added nats to the include directory during install [ci skip]

---

src/conn.c
src/natsp.h
test/list.txt
test/test.c

When getting an authorization violation after being connected
(will happen with server config reload), the client library will
now report the error if an error handler is set, but will not
close the connection.

[CHANGED] Authorization violation handling

---

src/unix/mutex.c

Needed to add `__aarch64__` to exclude usage of `rep` in spin lock.
Resolves #87

[ADDED] Support for ARM 6 [ci skip]

---

src/adapters/libevent.h
src/adapters/libuv.h
src/nats.h

Replaced `int socket` with `natsSock socket`.
Altough there was no warning compiling on Unix or Windows (where
a socket is defined as SOCKET as opposed to int), using natsSock
to be inline with the socket type on various platforms.
Updated the libevent and libuv headers accordingly.

[CHANGED] natsEvLoop_Attach socket parameter type

---

README.md

- Fixed 2 typos in README related to callback closures.
- Updated License copyright dates.
Resolves #96

[FIXED] Typos in README [ci skip]

---

src/conn.c
src/nats.c
src/sub.c
src/sub.h

Setting the new max value needed to be protected by the worker's
lock when the subscription is attached to a global message delivery
thread.

[FIXED] Possible missed auto-unsubscribe change under global message delivery

---

src/include/n-unix.h
src/include/n-win.h
src/nats.c
test/list.txt
test/test.c

If the error text that the library wanted to report was too long,
the error string would not be printed at all.
This is now fixed. The text will have `...` at the end to indicate
that it was truncated.

[FIXED] Windows - Error message not printed if too long

---

src/adapters/libevent.h
src/adapters/libuv.h
src/nats.h

Some newer headers (the adapters) did not have the block allowing
those headers to be used in C++
Resolves #109

[FIXED] Headers for C++ support

---

examples/examples.h

This was caused by unitialized variables for some of the stats
counters in the example programs.
Resolves #114
[ci skip]

[FIXED] Example programs sometimes report negative counts in stats

---

src/adapters/libuv.h

In libuv version prior to 2.0 (master), there is an API called
uv_poll_init_socket() that accepts a socket as last argument.
The uv_poll_init is doing some conversion and then call
uv_poll_init_socket, which can cause some issues for some users
on Windows platforms.
Starting libuv 2.0 (master), the uv_poll_init_socket API is renamed
as simply uv_poll_init (the two are consolidated).
The libuv adapter is therefore modified to use uv_poll_init_socket
if using the libuv 1.x version, and uv_poll_init otherwise.
Resolves #98

[FIXED] Use uv_poll_init_socket for libuv <= 1.x [ci skip]

---

.travis.yml
buildOnTravis.sh
src/conn.c
src/srvpool.c
src/srvpool.h
test/list.txt
test/test.c

The server pool was only growing when new servers were discovered.
Now, the client library updates its server pool based on server's
INFO protocols (true for server 1.0.6+).
The DiscoveredServersCB is still invoked only when new servers
are added (as in never seen as opposed to added back after leaving
the cluster).
Test has been running with local server at 1.0.7. The test will
not be active until executable is avail for download/install
on Travis.
Resolves #130

[IMPROVED] Server pool is updated following cluster updates

---

src/conn.c
src/conn.h
src/pub.c
test/list.txt
test/test.c

Don't use a connection's flusher thread if the connection sends
data as soon as possible.

[IMPROVED] No Flusher thread if connection has SendAsap option set

---

test/test.c

Some tests did still reference ssl_required (which has been
removed, tls_required is the proper field name). This has no
impact since in these tests, the value was set to false.

Removed use of ssl_required in test

---

src/conn.c
src/natsp.h
src/url.c
test/list.txt
test/test.c
test/tls_default_port.conf

- Allow URLs to not have scheme or port (in which case default
port 4222 is added).
- Switch to secure connection automatically if server requires
TLS.
- Fixed test on Windows.
Resolves #159

[IMPROVED] URL parsing allowing to skip scheme and default port

---

src/conn.c
src/conn.h
src/nats.c
src/natsp.h
src/sub.c
src/sub.h
test/test.c

API remain the same, just changed the implementation to reduce
use of threads and also works for sync subs and global delivery
thread pool.
Related to PR #161

Changes to drain mode implementation

---

src/conn.c
src/natsp.h
src/sub.c
test/test.c

- Calling drain (on sub or conn) when already in drain mode should
not return an error.
- Changed the implementation of the connection drain to not require
a thread (use timer instead).
- Added more tests, including auto-unsub.

Changes to Drain implementation

---

src/conn.c
src/conn.h
src/pub.c
src/stan/conn.c
src/sub.c
src/sub.h
test/list.txt
test/test.c

If user wishes to use global message delivery through use of library
deliver thread pool, internal subscriptions should not be part of
that since a slow user callback may then affect processing of
internal messages.
The Streaming library is using internal subscriptions for hearbeats,
acks, and pings and so this makes sure that these are not possibly
pooled and mixed with user callbacks.
The core library is also using a subscription for request/replies
and that subscription also should not be pooled.
Resolves #178

[FIXED] Ensure internal subscriptions not pooled

---

CMakeLists.txt
src/CMakeLists.txt
test/test.c

Here is the proper fix for the https://github.com/nats-io/cnats/pull/172.
Location of libraries and development files may be different when building for different platforms. CMake can handle this just fine, however, the current cmake configuration does not use these facilities. This merge request fixes that.

[IMPROVED] Use CMake variable for deployment destinations

---

src/conn.c
test/list.txt
test/test.c

This ensures that anything that is in the buffer is not only flushed
but that the server has processed anything that was sent by the
connection prior to the close call.
Resolves #188

[IMPROVED] natsConnection_Close() now internally calls FlushTimeout()

---

src/url.c

If format string is a string literal compiler can check that arguments are of correct type
> [ 14%] Building C object src/CMakeFiles/nats.dir/url.c.o
/home/erigtorp/src/github.com/nats-io/nats.c/src/url.c: In function ‘natsUrl_Create’:
/home/erigtorp/src/github.com/nats-io/nats.c/src/url.c:137:13: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
137 |             res = nats_asprintf(&str, fmt, copy, DEFAULT_PORT_STRING);
|

Allow compiler to statically check format string

---

src/err.h
src/nats.c

Did it using __attribute((format(printf())) as suggested by @rigtorp.
Fixed 2 cases where invocation of nats_setError() was wrong.
Resolves #223

[FIXED] Enabled compile type checking of error format args

---

src/conn.c
src/natsp.h
src/srvpool.c
src/srvpool.h
test/list.txt
test/test.c

In general we want to retry a connection that got an auth error
whether its a violation or expiration. However we want to close
the connection if we get the same error twice on same server.
Resolves #244

[FIXED] Handle auth errors on reconnects

---

src/conn.c
src/status.c
src/status.h
test/list.txt
test/test.c

Some new users have been incorrectly specifying a subject or
queue name with space that was not causing error but would prevent
messages from being received.
Added code that checks for invalid subject and queue name on
subscribe.
Resolves #245

[IMPROVED] Check for bad subject and queue name on subscribe

---

.travis.yml
src/nats.c

The missing header is included in one of the header we depend on
when building streaming. But when NATS_BUILD_STREAMING is set to OFF
the library would not build.
Added missing include and add a build with -DNATS_BUILD_STREAMING=OFF
to the build matrix.
Resolves #248

[FIXED] Missing header for offsetof() causing build issues

---

src/conn.c
src/natsp.h
src/srvpool.c
src/srvpool.h
src/util.c
test/list.txt
test/test.c

Similar to what has been done in Go client (https://github.com/nats-io/nats.go/pull/506)

Fix to handling of auth errors on reconnect

---

src/comsock.c
src/comsock.h
src/conn.c
src/include/n-unix.h
src/natsp.h
src/natstime.c
src/natstime.h
src/unix/sock.c
src/win/sock.c
test/test.c

Replaced use of select with poll() (for unix platforms).
Verified with user's provided reproducible repo that this solves
the issue.
Resolves #243

[FIXED] Possible memory corruption due to use of select()

---

.gitignore
src/conn.c
src/nats.h
src/natsp.h
src/opts.c
src/opts.h
test/test.c

Using this option, we can change the internal temporary buffer size, which is used for read/write and was hard coded as `DEFAULT_BUF_SIZE` in conn.c.
Increase of the size can improve the performance of read/write operations in some heavy load situations.
I would like to change the value in my use case, so could you consider it?

[ADDED] Ability to set IO read/write buffer size.

---

src/win/sock.c
test/list.txt
test/test.c

Changes made in #256 broke the case of "infinite" deadline in
natsSock_WaitReady() on Windows. Added a test to make sure
that works now.
Also updated a test that would leak file descriptors.
Related to #256
Resolves #243

Fixed natsSock_WaitReady() on Windows when given "no deadline"

---

src/nats.c
src/unix/thread.c
src/win/thread.c

We attach a destructor on process exit to do final cleanup of
the library. However, some NATS threads may have still be running
and accessing locks/etc.. that were freed. Make sure to retain/release
the library in NATS threads start/end.
Also natsThreadLocal_SetEx() in the unix implementation was not
checking the setErr that is set to false on library teardown which
was causing the library to be attempted to be opened in case of
error.

[FIXED] Possible core on process exit

---

src/nats.h
src/stan/conn.c
src/stan/copts.c
src/stan/stanp.h
test/test.c

Had to changes few things:
- No longer strdup to default URL when creating stanConnOptions
- Set the stan URL option to override any possible natsOptions
URL that could be set
- Update doc to specify that stanConnOptions_SetURL() takes
precedence to natsOptions_SetURL() if NATS options are passed
with stanConnOptions_SetNATSOptions().
Resolves #262

[FIXED] stanConnOptions_SetURL() had no effect

---

src/nats.h
src/opts.c
test/list.txt
test/test.c

- natsOptions_SetCertificatesChain()
- natsOptions_SetCATrustedCertificates()
These options allow to pass the certificate and key from a memory
buffer as opposed to read it from a file.
Resolves #267

[ADDED] Options to load CA and client cert/key from memory.

---

.travis.yml
README.md
examples/examples.h
src/comsock.c
src/comsock.h
src/conn.c
src/conn.h
src/include/n-win.h
src/nats.c
src/nats.h
src/natsp.h
src/opts.c
src/pub.c
src/stan/conn.c
src/unix/sock.c
src/win/sock.c
test/list.txt
test/test.c

Adds a write deadline for all socket write operations. It means that
a publish call could fail (with NATS_TIMEOUT) if the server is not
able to consume data (either not fast enough or connection is in
a state where it is not reported as closed, but transmission is
not happening).
Resolves #217
Resolves #215

[ADDED] natsOptions_SetWriteDeadline()

---

src/nats.h

This change makes clear that the pointer is a natsInbox.

Use the natsInbox typedef for natsInbox_Create and natsInbox_Destroy

---

src/CMakeLists.txt
src/nats.c

[FIXED] Windows: exclude DllMain when building static library

---

.travis.yml
install_deps.sh

Download the dependencies:
- NATS Server
- NATS Streaming Server
- libprotobuf
- libsodium
from nats.c.deps repository. These deps are installed only when
the travis cache is found to be empty.

Use new nats.c.deps repo for build dependencies on Travis

---

src/conn.c
src/pub.c
test/list.txt
test/test.c

Make sure we don't transfer possible write buffer to pending when
reconnecting.
Empty the pending buffer when flushing it on reconnect, regardless
if we get an error or not since we would otherwise take the risk
of sending duplicates.

[FIXED] Do not send partial protocols during a reconnect

---

src/adapters/libuv.h

Call process read event in natsLibuvPoll() when called with a
negative status.
Resolves #290

[FIXED] Libuv adapter

---

CMakeLists.txt

By default, the streaming API will be built which requires libprotobuf-c.
If this dependency is not found, a message was printed but the cmake
process would not fail. User would get error only when trying to
build the project.
Added a fatal error if deps are not found.
Resolves #292

[FIXED] Make cmake fail if required packages are not found

---

src/CMakeLists.txt

To use this library from a CMake project, you can locate it directly with find_package() and use the namespaced imported target from the generated package configuration:
```cmake
find_package(cnats CONFIG REQUIRED)
...
add_library(foo ...)
...
target_link_libraries(foo PRIVATE cnats::nats)
target_link_libraries(foo PRIVATE cnats::nats_static)
```

[ADDED] Other projects using CMake can include NATS C library with find_package()

---

CMakeLists.txt
examples/CMakeLists.txt
test/CMakeLists.txt

For instance, building static library only requires the user to
set `-DNATS_BUILD_STATIC_EXAMPLES=ON` otherwise a message is printed.
Replace the simple error message with a fatal error.

[FIXED] Make CMake fail for incompatible configuration

---

src/nats.h
src/natsp.h
src/stan/conn.c
src/stan/sub.c
src/sub.c
src/sub.h
test/list.txt
test/test.c

This allows users to set a callback that will be invoked when the
subscription is closed and message handler returns.
Resolves #302

[ADDED] natsSubscription_SetOnComplete API

---

README.md

Originally the outbound's buffer size was hardcoded. It is now possible
to set its size with `natsOptions_SetIOBufSize()`, so updating
the note in the README.
Resolves #306
[ci skip]

[FIXED] Note in README regarding outbound buffer size

---

src/conn.c
src/nats.h
test/test.c

if connected to an older server. In pair with the Go client.
Related to #312

Make natsConnection_GetClientIP() return NATS_NO_SERVER_SUPPORT

---

src/conn.c

[CHANGED] Reduce default flush timeout from 60 to 10 seconds.

---

src/srvpool.c
src/srvpool.h
test/test.c

If randomize is allowed, discovered URLs will be randomly added
to the pool of urls instead of always be appended.
See nats-io/nats.go#565

[FIXED] Randomize discovered server URLs if allowed

---

src/nats.h
src/stan/stanp.h
src/stan/sub.c
test/list.txt
test/test.c

Allows user to be notified when streaming subscription is closed
and there is no message handler about or in the process of being
invoked.
Resolves #318

[ADDED] stanSubscription_SetOnCompleteCB()

---

src/nats.h

The documentation stated that the callback could be invoked twice:
once during the initial disconnect and a second time when the
library failed to reconnect.
This behavior has been fixed since v1.2.10 such as the library does
not invoke the callback during the final close after failed
reconnect attempts.
Resolves #321
[ci skip]

[FIXED] natsOptions_SetDisconnectedCB() documentation

---

src/nats.h
src/opts.c
test/test.c

Supported only with OpenSSL 1.1

[ADDED] natsOptions_SetCipherSuites() to set ciphers for TLSv1.3

---

src/conn.c
test/list.txt
test/test.c

The goal is to invoked the error handler only once for several
dropped messages, that is, until the slow consumer marker for
a subscription is cleared. There was a defect in getting to
know when to fire the callback.
Typical case would be if there is a condition that trips the
slow consumer, the callback would not be invoked until after
a new message is received (and be still over the limit).
Resolves #327

[FIXED] ErrorHandler not properly invoked for SlowConsumer cases

---

src/asynccb.h
src/conn.c
src/nats.c
src/nats.h
src/natsp.h
src/opts.c
test/list.txt
test/test.c

This allows applications to be notified that the server it is
connected to is enterring lame duck mode. This is purely informative
as the library is currently not doing anything with this information.

[ADDED] natsOptions_SetLameDuckModeCB()

---

src/adapters/libuv.h
src/comsock.c
src/conn.c
src/nats.c
src/opts.c
src/parser.c
src/pub.c
src/sub.c
src/util.c

This commit makes nats.c buildable under stricter compiler flags.
Different use cases than libuv/NATS_HAS_TLS (probably) require more modification, but that's a start.

Remove unused variables

---

CMakeLists.txt
examples/publisher.c
examples/stan/sub.c
src/nats.c
src/natsp.h
src/stan/conn.c
src/stan/pub.c
src/stan/sub.c
test/test.c

Removed the `-Wno-unused-variable` so we get report in the future.

Removing more unused variables

---

README.md
src/stan/conn.c
src/stan/conn.h
src/stan/copts.c
src/stan/stanp.h
test/list.txt
test/test.c

Although it is strongly recommended for the application to set its
own handler, if no handler is set, the library will now use a default
handler that simply prints the error.
Resolves #342

[FIXED] Streaming: segfault if connection lost but no handler was set

---

src/msg.c

This patch fixes the following `cppckeck` warnings:
```
msg.c:842:18: note: outer condition: replyLen>0
if (replyLen > 0)
^
msg.c:845:22: note: identical inner condition: replyLen>0
if (replyLen > 0)
```
and it is obvious that `memcpy()` length parameter is already guarded by the outer condition.

Fix identical inner and outer 'if' condition

---

src/sub.c

Cppcheck report a possible memory leak due to an early return after a memory allocation.
```
sub.c:350:9: error: Memory leak: sub [memleak]
return nats_setError(NATS_INVALID_ARG, "Invalid bytes limit of %d", sub->bytesLimit);
```
Even if it cannot be triggered if options are setups using `natsOptions_Set*` helpers, the easy way to formally fix the issue is to validate the limit threshold (in bytes) before any memory allocation.

Fix possible memory leak due to an early return

---

src/url.c

GCC 10.0.1, when used with with `-fanalyzer`, reports:
`warning: leak of ‘url’ [CWE-401] [-Wanalyzer-malloc-leak]`
Issue is due to an early return. The easy way to fix it, without changing
too much, is to propagate the error code. In this way the function will
take care to free data structure calling `natsUrl_Destroy(url)`.

[FIXED] Possible memory leak when mem alloc failed creating an URL

---

src/msg.c

Some gcc compiler would report that strncpy could truncate. In
this specific instance, we know that it would not be happening,
but to remove the warning, replaced it with memcpy.
Related to #364

Replaced strncpy with memcpy

---

CMakeLists.txt
src/libnats.pc.in

Adding pkg-config support. This is particularly important for linking against C libraries from Swift.
I have tested this on Ubuntu 20.04 and macOS 10.15.

[ADDED] pkg-config support

---

src/natstime.c

Both `nats_Now()` and `nats_NowInNanoSeconds()` check for `CLOCK_MONOTONIC`, but they use `clock_gettime()` with `CLOCK_REALTIME`.

[FIXED]: check for CLOCK_MONOTONIC, but use of CLOCK_REALTIME

---

README.md
src/nats.h
src/nkeys.c
src/opts.c
test/list.txt
test/test.c

The option provides the public key and the file containing the
seed. This will be used during connect to load the file and use
the seed to sign the nonce. The memory where the seed is copied
will be cleared.
Also exposing a way for user to sign any input given an encoded
seed.
Resolves #369

[ADDED] natsOptions_SetNKeyFromSeed() and nats_Sign()

---

src/stan/conn.c
test/list.txt
test/test.c

If client is connected to a NATS server and the streaming server
is down, then the "no responder" feature would cause the server
to send an empty message in response to the PING request (which
was sent with PublishRequest()).
If message is empty, look for "no responder" status.

[FIXED] Streaming: pings may not report failures

---

src/conn.c
src/natsp.h
test/list.txt
test/test.c

Two issues: if using an event loop and SSL but the connection
fails before the event loop is attached, the library needs
to close the socket.
On normal socket shutdown, since there is no readloop in the
context of external event loop, ensure that the library closes
the socket properly.
Resolves #374

[FIXED] EventLoop: possible file descriptor leak

---

src/adapters/libevent.h

Wrong links from descriptions of `natsLibevent_*` functions'.

[FIXED] Typos in Libevent Adapter docs

---

src/conn.c
src/nats.h
test/list.txt
test/test.c

Check if `urls` list is `NULL`, before parsing it.
Internally the library will use `NATS_DEFAULT_URL` and therefore `NULL` become an an alias to `NATS_DEFAULT_URL`.
Patch include also a dedicated test case.

[FIXED]: segmentation fault when ConnectTo urls parameter is NULL

---

src/conn.c
src/opts.c
src/url.c
src/util.c
src/util.h
test/test.c

- URLs are now trimmed in natsOptions_SetURL and natsOptions_SetServers
- Invalid port reports an error
- Check for parse int overflow
Related to #385

Rework of URLs parsing

---

src/stan/sub.c
test/test.c

It should have returned NATS_INVALID_ARG for NULL sub and/or message.
Resolves #388

[FIXED] stanSubscription_AckMsg() returned NATS_OK for NULL sub.

---

src/conn.c
src/nats.h
src/natsp.h
src/opts.c
src/pub.c
test/list.txt
test/test.c

If enabled, any pending request (using new style) will fail with
NATS_CONNECTION_DISCONNECTED status.
Also fixed the failing of pending flush requests which was done
in the doReconnect thread while it should be done prior to
creating the pending buffer and starting the reconnect thread.
Resolves #391

[ADDED] natsOptions_SetFailRequestsOnDisconnect() option

---

src/conn.c
src/conn.h
src/nats.c
src/nats.h
src/natsp.h
src/sub.c
src/sub.h
test/list.txt
test/test.c

This addresses several issues related to drain:
- Subscriptions could not be closed (unsubscribe) by the user once
draining had started
- The natsConnection_Drain() and natsSubscription_Drain() were
possibly blocking since those functions would internally call
natsConnection_Flush().
The calls are now not blocking (the flush is done in a library
thread), the subscription can be closed while drain is in progress.
Two new APIs were added:
- natsSubscription_DrainTimeout(): this allows to specify a timeout.
When the timeout is reached and if the subscription is not fully
drained, the subscription will automatically closed.
- natsSubscription_DrainCompletionStatus(): once the user has verified
that the drain is complete, this function can be used to know if the
drain completed successfully or …

[FIXED] Subscription could not be closed while draining

---

src/pub.c
test/list.txt
test/test.c

In somce cases (like JetStream) it is possible that the server
rewrites the subject of the reply sent to a requestor. When the
requestor is not using the old style requests (meaning that there
is a connection level subscription on say `_INBOX.<nuid>.*` and
replies are dispatched based on the last token, the requests would
always fail since the response token would not be found in the map.

[FIXED] Receiving subject mapped replies with new style requests

---

src/comsock.c
src/util.c
test/test.c

Calling `freeaddrinfo()` with a `NULL` is undefined behavior.
Consider the [freeBSD manpage of freeaddrinfo(3)](https://www.freebsd.org/cgi/man.cgi?freeaddrinfo(3)):
```
IMPLEMENTATION NOTES
The behavior of freeadrinfo(NULL) is left unspecified by both Version 4 of
the Single UNIX Specification (“SUSv4”) and RFC 3493.  The current
implementation ignores a NULL argument for compatibility with programs that
rely on the implementation details of other operating systems.
```
Encountered this problem when targeting musl libc. See [the musl implementation here](https://git.musl-libc.org/cgit/musl/tree/src/network/freeaddrinfo.c). No-op is not guaranteed in the standard.
It is my first PR to `nats.c` so any feedback is very welcome.

Add a null check before freeaddrinfo()

---

src/comsock.c
src/util.c
src/util.h
test/test.c

**This is a draft PR.** Following the helpful feedback from @kozlovic (See #400) I want to wrap the culprit `freeaddrinfo()` with a null check. 
Sorry for disturbing you because of a minor nuisance, but could you please indicate in which header should I put it (since `util.h` is not included everywhere)?
I appreciate your help!

Code cleanup

---

src/stan/copts.h

The current defaults were too small and would cause a client to
mark the connection as lost after 15 seconds or so. This means
that a server restart or leadership change may lead to the client
dropping the connection.
Made the change so that the overall time the client keeps the
connection valid is as long as the server default ping settings.
Of course, user that use stanConnOptions_SetPings() are not affected.
This is only changing the default values.
Also, in the event that the server no longer has the client, the
client will detect that at the first ping interval, which is
5 seconds (the interval has not changed).

[CHANGED] Default Ping settings

---

src/conn.c
test/list.txt
test/test.c

When TLS connection is used, some internal state needed to be cleaned-up
after a disconnect before attempting to reconnect.
Resolves #412

[FIXED] Event loop reconnect issue with TLS connections

---

src/stan/sub.c
test/list.txt
test/test.c

If an application gets a timeout on a Subscribe() call, it does not
know if the server is actually going to process the request. The request
could have been just processed but the client timed-out before getting
the response back, or there is a bit of a backlog of requests in the
server and the request will be processed after the request times out
in the client.
If that happens, and if the application maintains its connection, then
it is possible that the server processes the subscription and keep that
subscription alive, although the application does not have an handle
on this subscription (the Subscribe() call has failed).
On timeout, the library will now send a request to close the subscription.
However, the protocol normally requires the AckInbox which is assigned by
the server and …

[FIXED] Streaming: Subscribe timeout should send a close request

---

src/url.c
src/util.c
src/util.h
test/test.c

This was introduced in v2.4.0.
Resolves #417

[FIXED] URL parsing returns "invalid port" if path after port

---

src/comsock.c

This is a regression introduced by implementation of WriteDeadline
in PR #268 (v2.1.0).
If a SSL read or write returns 0 for bytes read/written, the connection
should be reported as closed.
Resolves #415

[FIXED] TLS read/write not correctly reporting connection as closed

---

src/conn.c
test/list.txt
test/test.c

The accounting for subscription's pending bytes was wrong because
the whole message buffer was added (counting headers) but then
only the data portion was removed once message was dispatched.
Over time, this would lead to a subscription's pending bytes
possibly higher than the pending limit which would cause the
connection to always drop messages for this subscription.
Resolves #419

[FIXED] Slow consumer for subscriptions receiving messages with headers

---

src/conn.c
src/msg.c
src/nats.h
src/natsp.h
src/opts.c
src/stan/conn.c
test/test.c

Added an option to disable the "no responders" feature when connecting
to NATS Servers v2.2.0+.
Also made use of natsMsg_IsNoResponders() in a place in STAN code,
and optimized _liftHeaders so that we don't create the headers map
if there is no need to lift (no header in incoming message wire)
and if call was not made from Set or Add APIs.

[ADDED] natsOptions_DisableNoResponders() API

---

src/comsock.c
src/conn.c
test/list.txt
test/test.c

If a client is connected with TLS, then reconnects to a server
and the TLS hanshake is successful, but an error occurs as
part of the NATS connect handshake, then it would leave the
TLS connection in a bad state that would prevent to successfully
reconnect.
Resolves #425

[FIXED] TLS fails to reconnect after some protocol error

---

examples/getstarted/headers.c
src/msg.c
src/nats.h
test/test.c

Prior to v3.0.0, keys were changed to their canonical form, even
when being received from the server. This is no longer the case.
The case is now preserved and all header APIs are case sensitive.

[CHANGED] Headers keys are now case-sensitive

---

README.md
src/comsock.c
src/conn.c

Note that the 2 errors were actually false positive, since the
intent was really to assign, not to compare.
This was a trick to assign the waitMode based on the comparaison,
but to avoid confusion went to a more standard approach.
Added the LGTM badges.

Fixed errors/warnings from LGTM search

---

src/hash.c
src/hash.h
src/pub.c
test/test.c

In _respHandler, there is a case when we know the hash has a single
element and we want to use that one. We had to do something like:
```
natsStrHashIter_Init(&iter, nc->respMap);
natsStrHashIter_Next(&iter, NULL, &value);
natsStrHashIter_RemoveCurrent(&iter);
natsStrHashIter_Done(&iter);
```
(which, by the way, the "done" was missing).
This is now replaced with a single call:
```
natsStrHash_RemoveSingle(nc->respMap, NULL, &value);
```

Added nats[Str]Hash_RemoveSingle to remove the sole element of a hash

---

src/nats.c
test/test.c

The initial size was set to 2 and since lowering the pool max size
is a no-op, one would not be able to have a pool of size 1.
Changed the default size to 1.
Resolves #439

[CHANGED] Set default library delivery pool size to 1 instead of 2

---

src/comsock.c
src/comsock.h
src/conn.c
src/natsp.h
test/list.txt
test/test.c

The default behavior will now be to randomize the list of IPs that
we get after hostname resolution before attempting to connect.
The shuffling is disabled if the `natsOptions_SetNoRandomize` option
is enabled.
See https://github.com/nats-io/nats-architecture-and-design/issues/23

[CHANGED] Shuffling of IPs after hostname resolution

---

src/util.c

Include `<time.h>` was missing in `util.c`. I am building on a
Windows 10 VM with MS VS 2015 and did not have any issue, so not
sure if it is env or MS VS version specific.
Regardless, adding the include does not hurt and still works with
other platforms.
Resolves #453

[FIXED] Build on MS VS 2017

---

src/js.c
src/jsm.c
src/nats.h
test/list.txt
test/test.c

This is done to alert the user that consumer config is not changed
as one would expect.
Also fixed setting optional start seq/time needs to set the
proper deliver policy.

[IMPROVED] JS: Subscribe returns error if consumer config does not match

---

test/test.c

Servers will now reject a consumer create request that has FC
but no HB defined, so updating the tests.

Update JetStream test with FC to also set HB

---

src/conn.c
src/sub.c
src/sub.h
test/test.c

If the number of delivered messages is greater than the max value
specified by AutoUnsubscribe(), the library should remove the
subscription, and not send an UNSUB with a max value that is lower
than the current number of delivered messages.

[FIXED] AutoUnsubscribe() should remove sub if max <= delivered

---

examples/js-pub.c
examples/js-sub.c

- Made the created stream use the `-subj` as subject instead of
the stream name.
- Create stream (if not present) in the js-sub tool, not just
the js-pub tool.
- Add 1sec HB if flow control (`-fc`) parameter is set.

[UPDATED] JetStream examples

---

examples/js-sub.c
src/js.c
src/msg.c
src/msg.h
test/test.c

If a message is already ack'ed (except for natsMsg_InProgress()),
the library should not attempt to ack the message when the
callback returns.
It is even more important if the user called natsMsg_Nak() since
if the callback ack'ed the message, it would defeat the purpose
of the Nak.
Resolves #492

[FIXED] JetStream: auto-ack callback ack handling

---

src/conn.c
src/js.c
src/natsp.h
test/test.c

When a subscription is for a consumer with js_AckNone AckPolicy,
there is no point sending ACK messages to the server since these
would be ignored.
Resolves #494

[FIXED] JetStream: do not send acks for js_AckNone subscriptions

---

src/CMakeLists.txt

Using FetchContent to pull in the nats.c libraries does not work
as the location for include directories is not set to also look in
the source directories.
Since I am not installing nats.c locally, this changes will allow me to use the build artifacts in my project.

Add BUILD_INTERFACE to target_include_directories

---

examples/asynctimeout.c
examples/connect.c
examples/examples.h
examples/js-pub.c
examples/js-sub.c
examples/publisher.c
examples/queuegroup.c
examples/replier.c
examples/requestor.c
examples/subscriber.c
src/conn.c
src/js.c
src/nats.c
src/parser.c
test/test.c

Fixes following series of GCC warnings using `-Wformat-signedness/-Wformat`
`warning: format ‘%d’ expects argument of type ‘int’, but argument XX has type ‘unsigned int’ [-Wformat=]`

[FIXED] GCC warning on format strings

---

src/util.c

isxdigit() is equivalent, more compact and a bit faster.

[IMPROVED] Use isxdigit() instead of an explicit in-range check

---

src/util.c

There was a warning regarding a variable that may be uninitialized.
This was a false positive in that we would not call nats_Base64_DecodeInPlace()
if nats_Base64_DecodeLen() did not return NATS_OK. When returning
OK, `sl` would be initialized. Still, easy to fix that by just
setting `sl` to 0 during declaration.

Fixed warning about uninitialized variable

---

src/crypto.c
src/mem.h

When `libsodim` is not used, memory content is zeroized using a simple `memset()` and de-allocated using `free()`, so compiler may decide to remove `memset()`.
This patch add `secure_memzero()`, similar to `sodium_zero()`, to be sure to zeroize memory content also when `libsodium `is not used.

[IMPROVED] crypto: effectively zeroize mem. content

---

src/util.c
test/list.txt
test/test.c

The issue was actually caused by JSON parsing, so that could manifest
in other situations.
But for the reported issue, if a consumer was created with a filter
subject that contained the ">" wildcard and the user creates a
subscription with that same subject, the check for filter subject
match would fail because "test.>" is different than "test.\u003e".
Resolves #502

[FIXED] JetStream subscription using ">"

---

src/nuid.c

Fixes following Coverity issue:
Passing argument &globalNUID of type natsLockedNUID * and
argument 32UL (sizeof (natsNUID)) to function memset is suspicious
because sizeof (natsLockedNUID) /*40*/ is expected.

[FIXED] nuid: fix wrong sizeof in memset

---

test/test.c

Since it is a test condition the intent here is to compare and not to assign a value

[FIXED] test: fix assign instead of compare

---

src/conn.c

As s is not possible to be NAST_OK here.
Directly set s to NATS_CONNECTION_CLOSED.
Signed-off-by: yuchenlin <yuchenlin@synology.com>

Set return code on _connect() correctly

---

src/msg.c
src/util.c

Propagate error code to fix two unchecked return value issues reported by Coverity Scan.

[FIXED] Coverity Scan unchecked return value

---

src/js.c
test/test.c

The timeout was not re-evaluated when going back to low-level
natsSubscription_NextMsg().
Also fixed code and tests so that this works for all server versions
(2.6.6, 2.7.0 and current 2.7.1).

[FIXED] JetStream: Fetch() could take longer than the given timeout

---

src/conn.c
src/conn.h
src/js.c
src/nats.c
src/nats.h
src/natsp.h
src/opts.c
src/pub.c
src/stan/conn.c
src/stan/sub.c
test/list.txt
test/test.c

Ability to set a custom inbox prefix using the option:
`natsOptions_SetCustomInboxPrefix()`.

[ADDED] Custom inbox prefix option

---

src/kv.c
src/natsp.h
test/list.txt
test/test.c

When the JetStream context has a prefix, will use that for all
KV APIs as specified by ADR #19

[FIXED] KV: Support for JetStream prefix

---

src/js.c
src/jsm.c
src/nats.h
src/natsp.h
src/status.h
test/list.txt
test/test.c

[ADDED] JetStream: Nak delay and BackOff list

---

src/kv.c
src/kv.h
src/nats.h
test/test.c

Ability to get a key at a specific revision. Returns #NATS_NOT_FOUND
if no entry exists for this key at this revision.

[ADDED] kvStore_GetRevision() API

---

src/kv.c
src/nats.h
test/list.txt
test/test.c

There is a breaking change where kvStore_PurgeDeletes() accepts now
kvPurgeOptions instead of kvWatchOptions.
We needed from kvWatchOptions only the timeout, and as it standed, it was
bad since user could have passed watcher options that would have
affected the internal watcher that we make to collect delete markers.
Also, when invoking kvStore_PurgeDeletes(), the delete markers that
are older than a default of 30 minutes will be deleted, however more
recent ones will be kept. The data is always removed, even if a marker
is not.
The user can change the 30 minutes threshold using a new purge
option called kvPurgeOptions.DeleteMarkersOlderThan. If set to -1,
it restores the old behavior of deleting delete/purge markers,
regardless of their age.
Signed-off-by: Ivan Kozlovic …

[CHANGED] PurgeDeletes() will now keep markers that are less than 30min old

---

test/test.c

This makes sure that "Update" also uses the prefix when needed.

KV add kvStore_Update to the cross account test.

---

src/opts.c
test/test.c

This option used RSA specific OpenSSL APIs to load an RSA key.
This change will use any type of key.
Resolves #526

[CHANGED] natsOptions_SetCertificatesChain() now not limited to RSA key

---

src/js.c
test/test.c

This is due to a change in PR #516 that is making any Ack call
that passes an option to transform the call to sync calls if
option has a Wait value set.
The auto-ack callback was calling ack with the jetstream's context
options, which has always a Wait by default of 5sec.

JetStream: auto-ack callback would do sync acks

---

src/natsp.h
src/url.c
test/test.c

With missing port, we should default to 4222.
Resolves #530

[FIXED] Connection fails if URL is missing port

---

src/kv.c
test/list.txt
test/test.c

If running against a v2.7.2+ server, the discard policy of an
existing KV stream will be updated to discard new policy.

[UPDATED] js_CreateKeyValue updates discard policy to new

---

src/js.c
src/js.h
src/jsm.c
test/test.c

Some of the APIs were not properly checking for missing/invalid
stream and/or consumer names (presence of ".") which could lead
to API calls timing out because the server had no subscription
interest on the formed subject.

[FIXED] JetStream: stream and/or consumer name checks

---

src/jsm.c
src/nats.h
test/test.c

Namely for pull consumers: ability to override the replica count or storage type:
```
// Generally inherited by parent stream and other markers, now can be configured directly.
Replicas int `json:"num_replicas"`
// Force memory storage.
MemoryStorage bool `json:"mem_storage,omitempty"`
```
For the stream, this new StreamConfig option:
```
// Allow republish of the message after being sequenced and stored.
RePublish *SubjectMapping `json:"republish,omitempty"`
```
Where SubjectMapping is:
```
// SubjectMapping allows a source subject to be mapped to a destination subject for republishing.
type SubjectMapping struct {
Source      string `json:"src,omitempty"`
Destination string `json:"dest"`
}
```
Note: Removed consumer config's MaxRequestMaxBytes that was added
in PR #543 until we settle …

[ADDED] Stream RePublish and some ConsumerConfig new fields

---

src/js.c
src/msg.h
src/nats.h
src/natsp.h
test/list.txt
test/test.c

[FIXED] Ability to have async publish call timeout and invoke err handler
The new jsPubAckHandler takes precedence and is invoked even on
successful publish.
If the option MaxWait is specified on publish, then the library
will invoke the ack handler (or err handler) if a publish ack
is not received by then.
Resolves #538

[ADDED] jsPubAckHandler to handle "positive" publish acks

---

src/util.c

When formatting a date/time, the max lenght is 35 characters, so
the backing array should be 36 at least (for the terminal '\0').

[FIXED] Compiler warning for JSON get time

---

src/unix/mutex.c

> Error: selected processor does not support `yield' in ARM mode

fix armel build

---

src/sub.c
test/list.txt
test/test.c

In case where the subscription is destroyed by the user from the
message callback but it was the message that would cause the
limit to be reached, the UNSUB protocol was still sent to the
server.
Resolves #558

[IMPROVED] Suppress UNSUB when auto-unsub max is reached

---

src/js.h
src/jsm.c
src/kv.c
src/nats.h
src/natsp.h
src/util.c
src/util.h
test/list.txt
test/test.c

This starts with a new boolean in a stream configuration:
```
// Allow higher performance, direct access to get individual messages. E.g. KeyValue
bool  AllowDirect;
```
When a stream is created with that boolean, then it is possible
to use this API to get messages:
```
natsStatus
js_DirectGetMsg(natsMsg **msg, jsCtx *js, const char *stream, jsOptions *opts, jsDirectGetMsgOptions *dgOpts);
```
The possible options to get a message are:
```
typedef struct jsDirectGetMsgOptions
{
uint64_t        Sequence;               ///< Get the message at this sequence
const char      *NextBySubject;         ///< Get the next message (based on sequence) for that subject
const char      *LastBySubject;         ///< Get the last message on that subject
} jsDirectGetMsgOptions;
```
Signed-off-by: Ivan …

[ADDED] JetStream: Direct Get Message

---

src/jsm.c
src/nats.h
test/test.c

Since this feature was not released, made the change to the name
of the structure and added the HeadersOnly boolean to be on-par
with the server.
Related to #546

Changed RePublish from jsSubjectMapping to jsRePublish + HeadersOnly

---

src/js.c
test/test.c

New fields have been added in the consumer configuration, but the
function that checks that the existing consumer configuration matches
the configuration of a consumer that is looked-up duing a "subscribe"
call was not up-to-date.

[UPDATED] JetStream: consumer configuration check

---

src/nats.h
src/sub.c

This change adds the ability to get the subscription id / subject from a given natsSubscription instance.
This is done in a similar manner as the other "get functions" defined in nats.h (e.g. natsSubscription_GetStats which populates various fields such as pending bytes and dropped messages of a given subscription)

[ADDED] natsSubscription_GetID() and natsSubscription_GetSubject()

---

src/js.c
src/jsm.c
src/kv.c
src/msg.c
src/nats.h

This was causing compilation errors in C++ and was not really
adding any protection. It is stated in the doc that this value
should not be changed by the user prior to calling the destroy
function for those various lists.
Resolves #545

[CHANGED] `const int` to `int` for `Count` field in lists

---

src/kv.c
src/nats.h
test/list.txt
test/test.c

[ADDED] KeyValue: RePublish configuration

---

src/jsm.c
src/util.c
test/test.c

The direct get message time formatting was different that the regular
message get, but now they are the same so removed code that was handling
that special case.

Adjust to server direct get message time formatting

---

src/nats.h

Add note that js_DirectGetMsg() works only for server v2.9.0+

---

src/js.c
src/nats.h
test/test.c

If the durable name is not specified, the library will create an
ephemeral pull subscription.

[ADDED] JetStream: support for ephemeral pull subscription.

---

src/js.c
src/js.h
src/jsm.c
src/nats.h
test/test.c

When this is used, the library will send request to a different API subject space where the stream and consumer names are in the subject, along with a filter subject if one is specified.

[ADDED] `Name` in consumer configuration

---

src/nats.h
src/sub.c
test/test.c

Added comments in the js_Subscribe() calls that explains the behavior of auto created/deleted JS consumers.
It was the intent that auto-created JS consumers would be deleted only when explicitly calling unsubscribe/drain, similar to Go client.
However, in C, the user needs to call natsSubscription_Destroy to free memory. This call is calling internally natsSubscription_Unsubscribe (if the call was not made explicitly), but then we need to disable the deletion of the JS consumer in that case.

[FIXED] JetStream: natsSubscription_Destroy should not delete JS consumer

---

src/conn.c
src/js.c
src/msg.h
src/nats.c
src/pub.c
src/sub.c
test/test.c

When headers were introduced, the whole buffer (so data + hdr) was added as pending limits, but when messages were removed from the subscription, only the data part was removed, which caused an issue that was address in PR #420 by just accounting for the data size (not header).
Headers becoming more and more prevalent, it could be that a big part of message content is the headers, so we should probably count the headers size along with the data toward the subscription's bytes limit.

[CHANGED] Count message headers toward subscription limits

---

src/js.c
test/test.c

Since NATS Server v2.9.0, it is possible to create a pull consumer with an js_AckNone or js_AckAll acknowledgment mode, so removing the restriction at the API level.
Related to https://github.com/nats-io/nats-architecture-and-design/issues/156

[CHANGED] JetStream: Pull consumer can now use AckNone and AckAll

---

src/jsm.c
src/nats.h
test/test.c

Related to https://github.com/nats-io/nats-architecture-and-design/issues/120

[UPDATED] JetStream: Handle Tier limits in jsAccountInfo

---

src/jsm.c
test/test.c

When the option jsOptions.Stream.Info.SubjectsFilter is specified, the js_GetStreamInfo() would collect the subjects for the stream and return them in si->State.Subjects. However, the server had a 100,000 limit. Since server v2.9.0, pagination is supported therefore this call is going to under the cover get the info until all pages have been collected.
Related to https://github.com/nats-io/nats-architecture-and-design/issues/153

[CHANGED] JetStream: js_GetStreamInfo() now returns all subjects

---

src/util.c
test/test.c

[FIXED] Handling of JSON empty arrays

---

src/js.h
src/jsm.c
src/nats.h
test/test.c

New APIs to get the list of stream infos or names
- `js_Streams()` to get the list of stream infos
- `js_StreamNames()` to get the list of stream names
Both work with an optional stream subject filter.

[ADDED] JetStream: Stream infos/names list

---

src/jsm.c
src/nats.h
test/test.c

Allow KV like semantics to also discard new on a per subject basis

[ADDED] JetStream: `DiscardNewPerSubject` stream configuration

---

src/conn.c
src/js.c
src/natsp.h
test/list.txt
test/test.c

If the recreation of the ordered consumer were to fail, the library would invalidate the subscription and not try again.
This PR also changes the ordered consumer to use memory storage and replicas of 1. It also ensures that the ordered consumer is reset on missed heartbeats.

[FIXED] JetStream: Ordered consumers may not be reset in some cases

---

src/js.c
test/test.c

- Was not setting to MemoryStorage and Replicas of 1 on recreate
- Added test that checks for MemoryStorage after a reset
- Improved error reporting when failing to recreate the consumer
Related to #596

Ordered Consumr reset changes

---

src/jsm.c
test/test.c

The new configuration `Name` in `jsConsumerConfig` could be set when calling `js_AddConsumer`, but when getting the `jsConsumerInfo` response (from that call or any `js_GetConsumerInfo`, the `Name` was present in `jsConsumerInfo`, but was not in the `Config` field (a `jsConsumerConfig`). Although I am not sure this is needed, making sure that we unmarshal properly.

[FIXED] JetStream: `jsConsumerConfig.Name` was not unmarshal'ed

---

src/js.c
src/js.h
src/jsm.c
src/natsp.h
src/util.h
test/test.c

- It would reset when receiving hearbeats due to a bug on how I was checking for sequence mismatch (overriding ldseq/sseq/etc..)
- On reset, the consumer configuration would not be the same than the original. That was because I was not making a copy of the original consumer config.

[FIXED] JetStream: Ordered consumer issues

---

src/conn.c
src/js.c
src/natsp.h
test/test.c

Resetting some of the JS subscription needs to be done "in-place" as opposed to in the thread that attempts to recreate it.
Also speed up the reset on reconnect (as opposed to wait for missed hearbeats). Of course, it could be that the reset is for nothing if nothing was missing.

[FIXED] JetStream: Ordered Consumer could stop receiving messages

---

src/js.c

- Ensure that we set the jsi->consumer only on when the consumer's delivery subject matches the subscription's current subject. This is really because of tests with very low HB.
- Copy the consumer name in natsSubscription_GetInfo() in case the name would be freed during a reconnect.

More fixes to ordered consumer

---

src/conn.c
src/srvpool.c
src/srvpool.h
test/list.txt
test/test.c

If the user provides an URL with a username and password but the library discovers new servers and a disconnect occurs, the library would reconnect without the username and password. The option `natsOptions_SetUserInfo()` is normally recommended to solve this issue.
However, to be closer to other client libraries, this library will now save the username/password of an explicit URL and use those for implicit URLs (unless the aforementioned option is used).

[FIXED] Reconnecting to implicit URL would not use known user info

---

src/kv.c
test/test.c

Until now, the js_CreateKeyValue() call would possibly attempt to update the underlying stream to set some properties that were added from release to release. This had an unexpected side effect when a stream in a newer server has new properties that the application linked to an older library was not aware of and would not unmarshal. Even if a stream comparison (minus the property we would want to update) would return OK, it could be wrong because we would disregard new properties not known by the old client library.

[CHANGED] KeyValue: library will no longer try to update the stream

---

src/js.h
src/jsm.c
src/kv.c
src/nats.h
src/natsp.h
test/list.txt
test/test.c

Also updated state for proper Put() and Get() semantics with mirrors and across domains, e.g. leafnodes.
In practice when a mirror is across a domain, should be named the same as origin. That allows an app to run anywhere without anything special in terms of domains when binding to the KV itself.
(Removed dead-code following previous PR #607)

[ADDED] KeyValue: Support for Mirror and Sources

---

src/jsm.c
src/nats.h
src/status.h
test/list.txt
test/test.c

`jsStreamInfo` will now possibly have a list of stream alternates represented by a mirror:
```
typedef struct jsStreamInfo
{
(...)
jsStreamAlternate       **Alternates;
int                     AlternatesLen;
} jsStreamInfo;
```
The definition of a stream alternate is:
```
typedef struct jsStreamAlternate
{
const char              *Name;
const char              *Domain;
const char              *Cluster;
} jsStreamAlternate;
```
Also added some of the new JS specific error codes.

[ADDED] Stream alternates in `jsStreamInfo`

---

src/conn.c
src/conn.h
src/nats.h
src/natsp.h
src/opts.c
test/list.txt
test/test.c

I would say, this is very useful (I need it myself) because I am actually getting the JWT as env var in some docker container. I could write it to a file and then read that but it feels like unnecessary file I/O so I would rather directly read from memory.
I tested it personally and it works.
I can add UTs if you generally would accept this change (otherwise I'd rather save the time :)).

add natsOptions_SetUserCredentialsFromMemory

---

src/conn.c
src/msg.c
src/msg.h
src/nats.h
src/natsp.h
src/opts.c
test/list.txt
test/test.c

When json is used as messages' payload and simdjson library is used to parse them it is strictly desirable to have SIMDJSON_PADDING bytes in the end of payload buffer. Otherwise parsing can't be done in zero copy manner - simdjson will reallocate it and copy all the payload into a temporary buffer.
I would like to introduce a new NATS option which will provide ability to set such a custom padding in message delivery path.

[ADDED] Support padding when allocating buffer for incoming messages

---

src/conn.c
src/conn.h
src/js.c
src/natsp.h
src/opts.c
test/test.c

If no error handler is specified by the user, the library will use a default error handler that prints some error information to stderr.
If the user did not specify an error handler but does not wish to have anything printed to stderr, the user should set a dummy error handler that does not do anything.
Resolves #622

[CHANGED] Default connection error handler.

---

src/conn.c
src/js.c
src/kv.c
src/msg.c
src/util.c

According to the C standard, the argument to the <ctype.h> methods shall be representable as an unsigned char or shall equal the value of the macro EOF.  It is implementation-defined if the char type is signed or unsigned.
Signed-off-by: Sebastian Huber <sebastian.huber@embedded-brains.de>

[FIXED] Use of <ctype.h> methods if char is signed

---

src/comsock.c

This is potential buffer overflow vulnerability that can be exploited if server is controlled by an intruder.
If we detect that the buffer contains data then we have to reduce available space for the subsequent read operation. Otherwise read can overwrite memory past the buffer.
P.S.: Just discovered that this function is called only from one place and supplied buffer is always empty there. So actualy not a vulnerabilty but as it is written should be fixed in case anyone in future will use this function with non-empty buffer.

[FIXED] Bytes accounting while reading the INFO protocol

---

src/js.c
src/natsp.h
test/test.c

In some conditions, it could be possible for natsSubscription_Fetch() to return with a NATS_TIMEOUT error after said timeout elpased, but the next call would return almost immediately with a NATS_TIMEOUT again, but not after waiting for the specified timeout.
Resolves #631

[FIXED] JetStream: natsSubscription_Fetch() not honoring timeout

---

src/conn.c
test/test.c

This function, and natsConnection_GetConnectedServerId() would work only when the connection was fully connected. There is no reason to not make it work while the connection is reconnecting.
Resolves #635

[FIXED] natsConnection_GetConnectedUrl() not working during reconnect

---

src/conn.c
src/sub.c
src/sub.h

A race could cause the read loop to crash when processing a message for a subscription that is being removed in another thread.
Resolves #637

[FIXED] Crash processing inbound message for destroyed subscription

---

test/test.c

Signed-off-by: Ivan Kozlovic <ijkozlovic@gmail.com>

Fixed some flappers

---

src/pub.c
test/test.c

When using `natsOptions_SetRetryOnFailedConnect` option to connect and the library is not yet connected, calling `natsConnection_RequestMsg` with a message with headers would incorrectly return `NATS_NO_SERVER_SUPPORT` instead of `NATS_TIMEOUT`.
Resolves #644

[FIXED] natsConnection_RequestMsg() incorrectly returns NATS_NO_SERVER_SUPPORT

---

src/conn.c

This function returns number of bytes in the buffer.
It is incorrect to return value from `natsStatus` enum.
We could keep setting internal error code.
But in this case we should set error code for other cases too where we return `-1`

natsConnection_Buffered: fix returned value in case of error

---

src/conn.c

This is not a bug. But this is not a feature too.
I decided to merge PR into dev. But I can update PR to apply to master instead.

conn.c: _doReconnect: remove redundant assignment

---

src/conn.c

It happens when connection close was started and it signaled conditional variable before waiting for the same variable was started in reconnect thread.
The code example to reproduce the problem:
```c++
int main()
{
printf("Begin...\n");
natsConnection * connection = nullptr;
natsOptions * options = nullptr;
constexpr auto onConnectHandler = [](natsConnection *, void *)
{
};
natsOptions_Create(&options);
natsOptions_SetRetryOnFailedConnect(options, true, onConnectHandler, nullptr);
natsOptions_SetURL(options, "nats://localhost:54321");
const auto ts1 = nats_Now();
const natsStatus err = natsConnection_Connect(&connection, options);
const auto ts2 = nats_Now();
if (err == NATS_NOT_YET_CONNECTED || err == NATS_OK)
{
natsConnection_Close(connection);
}
const auto ts3 = nats_Now(); …
```

[FIXED] Missing connection status check causing unexpected delay during connection close

---

examples/micro-sequence.c
src/micro_endpoint.c
src/microp.h
src/nats.h

I never finished the schema implementation, but thankfully it's been removed, see https://github.com/nats-io/nats-architecture-and-design/issues/220 and https://github.com/nats-io/nats.go/pull/1270.
This PR removes it from the C implementation.

Removed the never-implemented schema

---

src/asynccb.c
src/conn.c
src/crypto.c
src/nats.c
test/list.txt
test/test.c

Since error handler is invoked asynchronously, if the user had destroyed the subscription, it was possible that the error handler would be presented with a subscription that was already freed.

[FIXED] Possible crash if error handler if subscription was destroyed

---

test/test.c

Fix was provided by outside contributor. Adding test that demonstrated the issue and ensures that it is now fixed.

Added test for fix from PR 654

---

src/micro.c
src/micro_endpoint.c
src/micro_monitoring.c
src/microp.h
src/nats.h
src/util.c
test/test.c

Matches https://github.com/nats-io/nats.go/pull/1277 and https://github.com/nats-io/nats-architecture-and-design/issues/220

[CHANGED] More verbose endpoint INFO

---

.travis.yml
buildOnTravis.sh
test/test.c

This PR prepares for testing with nats server v2.10 changes. It also fixes an issue with `sanitize=thread` that seemed to have appeared due to Travis `bionic` image changes.
- Use Ubuntu `focal` v20.04
- Added testing against nats-server `latest` release, and against the `dev` branch
- Changed gcc `sanitize=address` builds to Debug to get line numbers in the output
- Added `NATS_TEST_VALGRIND=yes` to `sanitize=thread` to reduce repeat counts and avoid timeouts

[CHANGED] Travis build changes

---

src/nuid.c

Trying to left shift any `uint32_t` value greater than `0x7FFFFFFF` by 32 places as an `int64_t` is technically undefined behavior. If this is hit during runtime, clang's ubsan will report "runtime error: left shift of 2147483648 by 32 places cannot be represented in type 'int64_t' (aka 'long')". Since this is occurs in a random number generator, the behavior is nondeterministic as well, though it seems to happen quite often.
I ran into this frequently while working on wrapping `nats.c` with `zig`, which enables Clang's `-fsanitize-trap=undefined` flag by default in debug builds. There may be other similar undefined behavior lurking in some of the other bit shifts, but this is the only place I've seen it pop up in the debugger so far.
See https://godbolt.org/z/z6aabseET for a reduction of …

nuid: use unsigned intermediate to avoid left shift undefined behavior

---

test/list.txt
test/test.c

There was an external contribution that fixed tls_available, but test was missing.
Also fixed some warnings in test.c.

Added test for recent tls_available fix

---

README.md

Looks like the Homebrew team moved the formulae in their repository back in August: [Homebrew/homebrew-core@442f9cc](https://github.com/Homebrew/homebrew-core/commit/442f9cc511ce6dfe75b96b2c83749d90dde914d2).
This PR readdresses the link to the `cnats.rb` formula.

Fix link to Homebrew formula

---

.travis.yml

gcc9 - Default - sanitize thread fails with following error:
```
CMake Error at /home/travis/deps/cmake-install/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
The C compiler
"/usr/bin/gcc-9"
is not able to compile a simple test program.
It fails with the following output:
Change Dir: /home/travis/build/nats-io/nats.c/build/CMakeFiles/CMakeTmp
Run Build Command(s):/usr/bin/make -f Makefile cmTC_613bf/fast && /usr/bin/make  -f CMakeFiles/cmTC_613bf.dir/build.make CMakeFiles/cmTC_613bf.dir/build
make[1]: Entering directory '/home/travis/build/nats-io/nats.c/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_613bf.dir/testCCompiler.c.o
/usr/bin/gcc-9   -fsanitize=thread  -o CMakeFiles/cmTC_613bf.dir/testCCompiler.c.o -c …
```

Disable a Travis-ci matrix run until Ubuntu bug resolved

---

buildOnTravis.sh

The "latest" was not working and would always use the one from nats.c.deps.
As for "main", I noticed lately that sometimes, we would get a binary of size 0, which would make all tests using the nats-server to fail. So make sure that we can run the server and get a valid version string. If not, repeat the test up to 5 times, otherwise fail the run.

Fixed download of NATS Server for latest/main

---

src/conn.c

If an error occurs when reading a protocol message during the connect phase, the library could spin appending a character into a buffer until the process would run out of memory.
Resolves #706

[FIXED] natsConnection_Connect can get stuck and consume all memory

---

src/util.c
test/test.c

Sometimes there is an authentication error due to a missing signature when `natsOptions_SetUserCredentialsFromMemory` is used:
```
[1] 2023/12/29 13:23:44.880932 [ERR] 172.18.0.1:33898 - cid:36 - authentication error
```
The problem is that _base64Encode doesn't do anything if the first byte is zero. Since the function works with strings and bytes, it makes sense to check `srcLen` instead of the first byte.

[FIXED] Random authentication error due to missing signature

---

src/nats.h
src/util.c
test/CMakeLists.txt

This is important for Windows platform.
I also fixed a cast issue in util.c (that was reported on Windows build). Some changes are also related to spaces at end of lines that were removed by my editor.
Resolves #714

[FIXED] Missing NATS_EXTERN in nats.h for some functions.

---

.github/workflows/update-docs.yml

@kozlovic @Jarema this is part of retiring `dev` and switching to releases from release branches. I am editing the release instructions now, will send the PR shortly for that. This GH action eliminates the need to re-generate the docs upon release.
This PR automatically updates the docs in `main` when needed (via a new PR). See https://github.com/levb/nats.c/pull/69 as an example, contains numerous changes caused by using a newer doxygen version.
Note that it will only fire when pushed to `main`, I debugged in my fork without the branch filter.
Example:

[ADDED] GitHub action to update docs

---

.github/workflows/update-docs.yml

- Use the same doc update branch for each target branch, avoid creating multiple PRs
- Add the source SHA, title to commit messages
- [skip ci] that works

[FIXED] More fixes for doxygen autoupdate

---

examples/js-pub.c
examples/js-sub.c

'SubjectsLen' is named in a way that suggests it can invoke the 'strlen' function, so I clarified in the comments that it represents the number of elements.

Modify JetStream examples (Add comments to SubjectsLen)

---

src/micro.c
src/micro_endpoint.c

Fixes #738 
The Go client [does not](https://github.com/nats-io/nats.go/blob/10381e1f115d3904df20bbefab2645e21bc2ac6c/micro/service.go#L786) prefix the name, it was a mistake. Now identify the EPs by subject, like the [Go client](https://github.com/nats-io/nats.go/blob/10381e1f115d3904df20bbefab2645e21bc2ac6c/micro/service.go#L835)

[FIXED] GH-738, do not prefix endpoint name with the group prefix

---

test/test.c

On `main`:
Fixed by retrying until the new value appears. Was unable to get the failure with the fix.

[FIXED] flapping test: Test_KeyValueMirrorCrossDomains

---

src/js.c

The `req->Batch` is changing inside the `_fetch` routine which led to an incorrect loop condition `while (... && count != req.Batch && ...)` and as a result heap buffer overflow in the expression `msgs[count++] = msg;` at line 1921.
Address sanitizer report:
```
==4065175==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x51500002bc00 at pc 0x555555c073c5 bp 0x7fffe6a60c00 sp 0x7fffe6a60bf8
WRITE of size 8 at 0x51500002bc00 thread T1070
#0 0x555555c073c4 in _fetch /src/nats.c-3.8.0/src/js.c:1953:31
#1 0x555555c07a95 in natsSubscription_Fetch /src/nats.c-3.8.0/src/js.c:2028:9
...
0x51500002bc00 is located 0 bytes after 512-byte region [0x51500002ba00,0x51500002bc00)
allocated by thread T1070 here:
#0 0x5555556e2ae8 in calloc (/src/nats_test+0x18eae8) (BuildId: …
```

[FIXED] Fix heap buffer overflow in _fetch

---

test/test.c

Fixes test failure against server `main`

[TEST only] increased Test_KeyValueMirrorCrossDomains timeout value

---

codecov.yml
src/js.c
src/jsm.c
src/kv.c
src/mem.h
src/nats.h
src/util.c
src/util.h
test/list.txt
test/test.c

Added `kvStore_WatchMulti`, `js_SubscribeSyncMulti`, `js_SubscribeMulti` APIs to use multi-subject consumers.

[ADDED] kvStore_WatchMulti, js_Subscribe[Sync]Multi

---

src/conn.c
src/nats.h
src/natsp.h
test/list.txt
test/test.c

Simplified version of https://github.com/nats-io/nats.c/pull/756

[Added] natsConnection_Reconnect

---

.github/workflows/on-pr-debug.yml
.github/workflows/on-push-release-extra.yml
.github/workflows/on-push-release.yml

`main` and `release_**` will still run 3x, but all PR jobs will use 1x

[CI only] run tests once, not x3 except for main, release

---

test/test.c

https://github.com/nats-io/nats-server/pull/5482/files#diff-c6e9a3ce0d55948f2e7ea75a4de309986654f2ab11e0f8750625b88b28bd9ebfR2833-R2838 broke this test. The test was faking a JetStream-delivered message, resulting in inaccurate ACKs being sent to the server. Disabled auto-ACKs for the relevant messages to avoid messing up the server state, and the test is now passing.

[TEST ONLY] Fixed Test_JetStreamSubscribeIdleHeartbeat

---

test/test.c

Fixed test_JetStreamInfoAlternates flapper

---

test/test.c

Fixed flappers and test_SSLHandshakeFirst by skipping if server is < 2.10.0

---

.github/workflows/build-test.yml
.github/workflows/on-pr-debug.yml

Streamlined and fixed the test matrix for coverage, sanitize, and environment variable/commpile flag configurations.

[CI only] Streamlined/fixed sanitize/coverage matrices

---

.github/workflows/build-test.yml
.github/workflows/on-pr-debug.yml
test/test.c

This test would fail unless we force host verification, so adapt test to take into consideration the expected result based on the build environment variable.

Fixed test SSLVerifyHostName when build NATS_FORCE_HOST_VERIFICATION=OFF

---

README.md

Hi, 
I just found that nats.c is also available [here](https://conan.io/center/recipes/cnats?version=3.8.0), so I added it to the README.
Best,
Matthias

nats.c is available on conan.io/center

---

src/util.c
test/test.c

A customer ran into this issue, no ticket opened.

FIXED: nats_GetJWTOrSeed to understand Windows \r\n lines

---

doc/DoxyFile.NATS.Client
src/nats.h

Mostly doxygen changes, renames 2 (new) callback types that were inappropriately named `nats...`, should've been `js_`.
The only way I know to see the HTML changes is to run Doxygen locally, in this branch.

[DOCS ONLY] fixed documentation changes in preparation for v3.9 release

---

src/adapters/libevent.h
src/adapters/libuv.h
src/conn.c
src/nats.h
test/test.c

The socket was closed by the NATS library itself, which could cause some issue when the event loop thread would still be polling it. We now defer to the event loop adapter to make sure that the event loop library is done polling before invoking a new function that will take care of closing the socket.
I have updated the event loop test (that simulates what our adapters are doing). The mockup event loop implementation is a bit too simplistic but should be ok for now. If we have issues, we would have to make the events a linked list.
Resolves #814

[FIXED] EventLoop: Socket now closed only after event loop done polling

---

src/kv.c
src/nats.h
test/test.c

As requested on Slack, https://natsio.slack.com/archives/C01AWP40KGF/p1729791332242309

Added UpdatesOnly to kwWatchOptions

---

examples/js-pub.c
examples/js-sub.c

Also clarify that `stream` parameter is actually needed.

[FIXED] Examples: Add missing 'stream' and 'durable' params in usage

---

test/test.c

Since this server PR: https://github.com/nats-io/nats-server/pull/6154 the error occurs only if MaxDeliver is specified, but it is strictly lower than BackOff length. So fix the test by lowering it to 1.
Signed-off-by: Ivan Kozlovic ivan@synadia.com

Fixed JetStreamBackOffRedeliveries test

---

src/glib/glib.c

add stddef include to fix error build with NATS_BUILD_WITH_TLS=OFF NATS_BUILD_STREAMING=OFF NATS_BUILD_USE_SODIUM=OFF

[FIXED] build error (#819)

---

CMakeLists.txt

Credit goes to @mtmk with the proposed fix and verification that it works on mingw.
I have verified that the change still works when building on my Windows VM, so I don't expect windows users to have any issue with that.
Resolves #827

[FIXED] Build: failure with mingw

---

src/micro.c
test/test.c

Saw that looking at the build log in GitHub actions:
```
/home/runner/work/nats.c/nats.c/src/micro.c: In function ‘micro_add_endpoint’:
/home/runner/work/nats.c/nats.c/src/micro.c:153:16: warning: pointer used after ‘free’ [-Wuse-after-free]
153 |         return microError_Wrapf(micro_ErrorInvalidArg, "invalid subject '%s' for endpoint '%s'", fullSubject, cfg->Name);
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/runner/work/nats.c/nats.c/src/microp.h:18,
from /home/runner/work/nats.c/nats.c/src/micro.c:16:
/home/runner/work/nats.c/nats.c/src/mem.h:28:29: note: call to ‘free’ here
28 | #define NATS_FREE(p)        free((p))
|                             ^~~~~~~~~ …
```

[FIXED] microService_AddEndpoint() could crash if subject is invalid

---

src/micro_monitoring.c

The default handler was invoked with a request that was already checked to have a service associated. The handler was extracting the service (that was not needed) and had an incorrect check such as `if ((m == NULL) || (m == NULL))`.
Resolves #833

[FIXED] Default statistics handler of microservice had unnecessary check

---

src/nats.h
src/natsp.h
test/check_cpp/check_cpp.cpp

Namely `nats_OpenWithConfig` and `natsConnection_Reconnect`.
Also normalized the `NATS_EXTERN <return type>` in one line and the function name on the next line.
Updated the C++ compile test since it was failing on my mac env, and modified `nats_StringEquals` that was triggering a warning on my Windows VM build.
Resolves #835

[FIXED] Added missing `NATS_EXTERN` on some functions.

---

src/conn.c
src/js.c
src/sub.c

3 locations:
1. nc->cur checked for NULL, but after use it without check
2. serverUrls can be null and dereferenced in do-while cycle
3. msg can be null, if sub->draining false. I just added check, maybe someone advice how to fix it better

fix: some nulls checks

---

src/js.c

If we failed in natsThread_Create now we do double free for oci.
I added free on oci part for this and assigns NULL to avoid it.

fix: double free and deref after free in js.c

---

src/util.c

I hope I catch logic of this function.
We iterate over arr->values, and If allocation fails we have `i` to know how many already allocated. 
And after goes 0..i to clear allocated strings before.
But for-cycle do not use `j` which increment, and use `i`  `i`-times

fix: typo in clear routine

---

src/jsm.c

I see some problem around this code fragment.
What if this calloc returns NULL?
https://github.com/nats-io/nats.c/blob/07df538b422a8bb3377173d26db238f9b12e73ec/src/jsm.c#L4015
- we set `s = nats_setDefaultError(NATS_NO_MEMORY);` - ok
- we skip cycle because s raised - ok
- we assign len for clone - bad 
https://github.com/nats-io/nats.c/blob/07df538b422a8bb3377173d26db238f9b12e73ec/src/jsm.c#L4023
- go here:
https://github.com/nats-io/nats.c/blob/07df538b422a8bb3377173d26db238f9b12e73ec/src/jsm.c#L4029
- Free NULL - ok
https://github.com/nats-io/nats.c/blob/07df538b422a8bb3377173d26db238f9b12e73ec/src/jsm.c#L3027
- Free NULL->`*some offset*` - bad
https://github.com/nats-io/nats.c/blob/07df538b422a8bb3377173d26db238f9b12e73ec/src/jsm.c#L3025
Counter examples (why my patch looks like …

fix: better cleanup if js clone config fails

---

README.md
src/nats.h

@Jarema please note that the `Micro` in the name is still there. LMK if it's ok to stay as is, or if we should rename to `Service`.

Removed all remaining EXPERIMENTAL (micro)services documentation references

---

src/srvpool.c

Don't check ptr, check value of ptr

fix: srvpool typo

---

src/conn.c
src/nats.h
src/natstime.c

Currently, on Windows, the RTT (round-trip time) resolution is too low because it doesn’t support sub-millisecond precision. To address this, I propose we use the `QueryPerformanceCounter` API, which offers higher resolution. Additionally, monotonic timers are preferable for time interval measurements. Unlike the real-time clock, which isn’t guaranteed to be incremental and can even move backward, monotonic timers ensure consistent and reliable results.

Use monotonic timer for RTT

---

.github/workflows/build-test.yml
.github/workflows/on-pr-debug.yml
CMakeLists.txt
README.md
src/conn.c
src/nats.h
src/natsp.h
src/opts.c
test/test.c

Fixes #857. An alternative to @mtmk's proposal.
This new API introduced in #826 created a build issue, as @ckasabula had warned.
I propose that for now we mark it as `EXPERIMENTAL` and hide behind a `NATS_WITH_EXPERIMENTAL` env. variable as this PR implements. This will fix the immediate widespread build issue.
Then I see 2 paths to fix this in a better way.
A) Go back to what @ckasabula originally proposed (+apologies!!!)
B) Leave the code "as is", but replace `NATS_HAS_TLS` with `NATS_NO_TLS ` since I believe it is purely an internal variable. That would alleviate the issue for all clients compiling the default TLS on. @kozlovic do you think it'd work?

[FIXED] make natsOptions_SetSSLVerificationCallback experimental

---

src/nats.h
src/opts.c

This adds support for loading certificates from a directory. For now, I'm patching the library during the build of our container, but it would be nice if a dedicated function were available instead.

Add support for loading CA trusted certificates from directory

---

.github/workflows/on-push-release-extra.yml

This job now fails since these older compilers do not appear available on Ubuntu 22.04 (after https://github.com/nats-io/nats.c/pull/864)
I scanned the README and the docs and we do not appear to make any claims as to the specific compiler version support.

[BUILD ONLY] removed the older compilers jobs, n/a on Ubuntu 22.04

---

.github/workflows/on-pr-debug.yml

This is caused by binary only tag no being able to processed by the nats-server download system

[BUILD ONLY] Fix Windows build to use server main

---

src/micro.c

Hi, I think we should check result of calloc instead calling argument.

fix: better alloc error check

---

src/status.c
src/status.h

For status **NATS_PIN_ID_MISMATCH** in array **statusText** its description was missing. 
Therefore, calling the function **natsStatus_GetText(NATS_PIN_ID_MISMATCH)** would result in accessing an invalid address.

fix: add missing statusText string

---

src/conn.c

We had several issues around the introducing of a verification callback. We reverted to use a `NATS_WITH_EXPERIMENTAL` build flag, but still, as part of the rewrite, there was something of the like:
```
SSL_verify_cb cb = _collectSSLErr;
```
Prior to 3.10, we would have called `SSL_set_verify(ssl, SSL_VERIFY_PEER, _collectSSLErr);` which was not causing an issue. The above would when building with OpenSSL prior to 1.1.1.
So move the `cb` initialization as a `SSL_verify_cb` only when under the experimental flag, otherwise, invoke the same code we had prior to 3.10.
Resolves #877

[FIXED] Build: Unknown type name SSL_verify_cb

---

src/glib/glib_timer.c
src/glib/glibp.h
test/test.c

We use a linked list to hold timers. They are ordered by absolute time. Inserting a timer was always looking for the spot starting at the beginning. We now check first if it should be added directly at the end of the list, which in most cases - say creating new connections that creates a timer for sending PINGs, they will likely be sequential.
Added a test that shows that for 100,000 timers, the time spent is now very small.

[IMPROVED] Timer insertion

---

src/conn.c
src/js.c

When publishing a JetStream message asynchronously but with a publish max wait, we would schedule an internal timeout message to our internal subscription to handle ack timeout, even if the message was actually already ack'ed. The handler for the ack would disregard that timeout message because it would not be found in the hash table but we optimize here by not scheduling if the message has already been handled in `_handleAsyncReply()`.
This was reported in #880

[IMPROVED] JetStream: handling of publish async timeouts

---

src/micro.c
src/micro_monitoring.c
test/test.c

The field was incorrectly marshaled as a string duration instead of a number (nano seconds). Also, the computation of the average time would not take into account the possibility of having zero number of requests, which would produced a NaN and an invalid number during marshal.
Added test to check statistics before any request and that the field is a proper number (not a string). Also verified that it now works well with the NATS CLI.
Resolves #890

[FIXED] MicroServices: Wrong marshaling of `average_processing_time`

---

src/nats.h
src/opts.c
test/test.c

If a `natsOptions` object is configured with TLS/SSL, once it is passed to a `natsConnection_Connect` call, the options cannot be modified because internally we use a `SSL_CTX` that cannot be modified once `SSL` object are created from it.
We used to detect that the options were in use but instead of returning an error, we would dissociate the context from connections and create a new `SSL_CTX` for this `natsOptions` object. It "worked" in that connections were safely not using a context that could change, but it was wrong because the `SSL_CTX` would obviously be created empty and not reflect the previous modifications that were made.
It is very unlikely that users would create a `natsOptions`, pass it to connections and then modify it, but this PR makes it explicit that using it this way …

[FIXED] Options: don't allow modifications if SSL configured and in use.

---

src/comsock.c
src/conn.c
src/natsp.h

The NATS C Client design is to have a thread reading data from the socket and a flusher thread writing data, or simply writing from the user thread if buffer is full.
For a given connection, when SSL is configured, the connection has an OpenSSL `SSL` object, and that object was shared in these threads to perform `SSL_read` and `SSL_write`, which technically is wrong. Some thread sanitizer may report that.
This PR adds a mutex that will protect the calls to SSL_read/SSL_write and SSL_get_error when returned bytes is negative (that indicate an error).
The socket has to be non-blocking, which we now make sure it is when the connection is SSL.
Local benchmark has shown no difference between the main and this PR. Even if a performance degradation would have been observed, this is apparently …

[FIXED] SSL: Protect SSL_read/SSL_write with mutex.
