nats-io/nats.c

src/buf.c
test/test.c

There was no check for the new size of the buffer, which caused natsBuf_Expand to return NATS_INVALID_ARG. We are now returning NATS_NO_MEMORY when we detect that the new size is going to be over the 2GB limit.

Fix status when append to buffer goes over 2GB

---

examples/replier.c
src/conn.c
src/conn.h
src/nats.h
src/natsp.h
src/pub.c
src/sub.c
src/sub.h
test/list.txt
test/test.c

Performance tests show that there is no need for this call at this
stage. Deprecating now and will remove in the future.

[DEPRECATED] natsSubscription_NoDeliveryDelay

---

src/include/n-unix.h
src/srvpool.c
test/test.c

Consider localhost:port, 127.0.0.1:port and [::1]:port all equal
when checking if the url is already registered.

Look for "duplicates" before adding to the server pool

---

src/nats.c
src/natsp.h
test/list.txt
test/test.c

User @mpodanow contributed the fix for a crash in nats_updateErrStack.
Adding a test to make sure that we no longer crash and result
is as expected.

Added test case for PR #56

---

src/conn.c
test/test.c

In the reconnect thread, the connection's field reconnectThread
was set to NULL, lock released in order to flush.
If at that time the connection was closed, since reconnecThread
was NULL, the thread doing the close will not join the reconnect
thread and release the connection. When the reconnect thread
would try to flush, it would possibly crash since the connection
object was being freed.
Resolves #77

[FIXED] Possible crash after a reconnect

---

src/conn.c
src/conn.h
src/natsp.h
src/pub.c
test/list.txt
test/test.c

Also fixed a missing retain/release and add connection's closed
status in condition when waiting for wildcard subscription to be
created.

Add pooling to new request/reply pattern

---

README.md

[FIXED] Typos and formatting in README.md [ci skip]

---

CMakeLists.txt
README.md
examples/getstarted/CMakeLists.txt
examples/getstarted/asyncsub.c
examples/getstarted/pubbytes.c
examples/getstarted/pubmsg.c
examples/getstarted/pubstr.c
examples/getstarted/replier.c
examples/getstarted/requestor.c
examples/getstarted/syncsub.c

Added some very simple examples for people getting started with
the NATS C Client.
Resolves #99

[ADDED] Get started examples

---

src/include/n-unix.h
src/include/n-win.h
src/nats.c
src/natsp.h
src/util.c
test/test.c

On Windows, there was some issue if the locale was not en-US that
would prevent a client to connect to the server.
Resolves #105

[FIXED] Windows - issue with locale

---

README.md

[ADDED] FAQ in README [ci skip]

---

src/include/n-unix.h
src/nats.c

The PR #108 addressed the issue for only for Windows. This PR
addresses the issue for macOS and Linux platforms too.
Resolves #105

[FIXED] Unable to connect depending on locale

---

CMakeLists.txt
examples/examples.h
src/include/n-unix.h
test/test.c

Thanks to @martende in PR #122 for reporting fixing the issue.
Other changes were required to build on all other platforms.

[FIXED] Build issues on glibc 2.26 due to xlocale.h

---

install_gnatsd.sh
src/conn.c
test/list.txt
test/test.c

[FIXED] Parsing of protocol right after the first PONG

---

test/list.txt
test/test.c

This requires that the release is done by first pushing a new tag,
not create the release/tag directly from GitHub.

Added test to ensure version and tag match on new release.

---

README.md
src/unix/sock.c
test/test.c

[ADDED] Document threading model in FAQ [ci skip]

---

README.md

Prepare for next release [ci skip]

---

src/unix/mutex.c

We were running into compile errors in `src/unix/mutex.c`:
```bash
Error: unrecognized opcode: `rep'
```
Which, the comments suggest is expected for ARM and ARM64, but PowerPC also doesn't have the instruction used. 
There are several good kernel macro to use, like `spin_until_cond` or `cpu_relax`, but they either are too new in the kernel, or require the kernel headers, which is something I didn't think the project wanted to depend on.
I also tried to find a good pthread or glibc alternative, but came up short. So I borrowed from [an implementation of `cpu_relax` in boost](https://www.boost.org/doc/libs/1_68_0/boost/fiber/detail/cpu_relax.hpp) to implement a few more branches to support more architectures.
I didn't test this to see if it actually accomplishes anything more than just …

added additional architecture support when mutex locking with spin

---

src/conn.c
src/nats.h
src/natsp.h
src/opts.c
test/list.txt
test/test.c

Aligning cnats with changes from https://github.com/nats-io/go-nats/pull/405

[ADDED] TokenHandler option for expiring token support

---

.gitignore
.travis.yml

Some of the tests are broken on newer versions of GCC

Add more compilers to CI build

---

.travis.yml
install_servers.sh
src/buf.c
src/conn.c
src/nats.c
src/util.c
src/util.h
test/test.c

This is based off https://github.com/nats-io/nats.c/pull/225, thanks to @rigtorp for the contribution!
Fixed some code based on reports from fsanitize and use of newer compilers.

Added more recent compilers in Tavis builds

---

CMakeLists.txt
examples/CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt
test/dylib/CMakeLists.txt

[ADDED] CMake options to build static and/or library

---

src/win/sock.c

Removed some debug code from earlier PR [ci skip]

---

.travis.yml
CMakeLists.txt
README.md
install_deps.sh
src/CMakeLists.txt
src/conn.c
src/crypto.c
src/crypto.h
src/nats.c
src/nkeys.c
src/nkeys.h
test/test.c

Optionally builds with libsodium for encryption code.

[ADDED] Support for libsodium

---

src/conn.c
test/list.txt
test/test.c

Clear last error on successful reconnect and update some tests

---

src/parser.c
test/test.c

[FIXED] Message parsing with extra spaces

---

src/parser.h
test/test.c

[UPDATED] Increase the default max control line

---

src/conn.c
src/nats.h
src/natsp.h
test/list.txt
test/test.c

Returns the IP as determined by the server when accepting this
connection.

[ADDED] natsConnection_GetClientIP()

---

src/conn.c
src/nats.h
test/list.txt
test/test.c

Returns the round trip time between the client and server.

[ADDED] natsConnection_GetRTT()

---

.travis.yml
src/conn.c
src/hash.c
src/stan/conn.c
src/stan/conn.h
src/stan/sub.c
test/test.c

[FIXED] Some memory alignment issues for ARM32

---

src/conn.c
src/nats.h
src/natsp.h
src/opts.c
src/opts.h
src/srvpool.h
test/list.txt
test/test.c

Adds a jitter option on top of reconnect wait delay, and an
option to specify custom reconnect delay.

[ADDED] ReconnectJitter and CustomReconnectDelay

---

src/msg.c
src/nats.h
src/stan/msg.c
src/stats.c

This allows the usage of read-only methods for const pointer.

Improve const correctness

---

test/test.c

Was missing this unused variable with config that disables TLS

---

src/conn.c
src/nats.c
src/natsp.h
src/natstime.c
src/stan/pub.c
src/sub.c
src/unix/cond.c
src/win/cond.c
test/test.c

[FIXED] Ensure that large timeout does not overflow wait time

---

src/comsock.c
test/test.c

Say user defined ordering as 64 (IPv6 first, then v4), but the
server is listening only to IPv4. If the connect has a timeout
and the wait for connect ready times out (which is the case on
Windows), then there would be no chance to connect.
This PR now will split the total timeout to the number of IPs
that will be tried. This allow the above scenario to work.

[FIXED] Connections with IP ordering and deadlines

---

README.md
examples/getstarted/headers.c
src/conn.c
src/conn.h
src/hash.c
src/hash.h
src/msg.c
src/msg.h
src/nats.c
src/nats.h
src/natsp.h
src/parser.c
src/parser.h
src/pub.c
src/srvpool.c
src/stan/pub.c
src/stan/sub.c
test/list.txt
test/test.c

[ADDED] Headers support

---

src/conn.c
src/conn.h
src/natsp.h
src/pub.c

Simplify creation of connection response mux

---

src/adapters/libevent.h
src/nats.h

[FIXED] Libevent deadlock with stale connection

---

README.md

Add note in README regarding JetStream

---

examples/examples.h
examples/libevent-pub.c
examples/libevent-sub.c
examples/libuv-pub.c
examples/libuv-sub.c
examples/publisher.c
examples/queuegroup.c
examples/replier.c
examples/requestor.c
examples/stan/pub-async.c
examples/stan/pub.c
examples/stan/sub.c
examples/subscriber.c
src/buf.c
src/hash.c
src/natsp.h
src/stan/sub.c
src/unix/mutex.c

Trying to fix reports from https://lgtm.com/projects/g/nats-io/nats.c?mode=list

Fixes based on SearchLGTM report

---

src/conn.c
src/natsp.h

Second take on event loop file descriptor leak.
This is what I think is a simpler version of #375.
Resolves #374

[FIXED] EventLoop: possible file descriptor leak

---

README.md
src/msg.c
src/msg.h
src/pub.c
test/test.c

Also update link to travis-ci.com instead of .org in README.

[FIXED] Support description for header status line

---

.travis.yml
src/msg.c
test/test.c

Tweak the code to parse header status description

---

src/conn.c

natsConn_create() is taking ownership of the options. If anything
fails before that point, we need to destroy the options that have
been created before that point.

Destroy options in case of failure before natsConn_create runs

---

test/test.c

- Make testCond() exit from the test, so no need to check between
steps in the same test if previous condition was ok.
- Use IFOK() in lot of places

Reworked test framework

---

src/comsock.c
src/comsock.h
src/conn.c
src/include/n-unix.h
src/nats.h
test/list.txt
test/test.c

This returns the connection's local IP and port.
Resolves #402

[ADDED] natsConnection_GetLocalIPAndPort() function

---

test/list.txt
test/test.c

Add test for parse INFO fix

---

.travis.yml
CMakeLists.txt
install_deps.sh

Update CMake to more modern version

---

src/conn.c
src/pub.c
test/test.c

In the race condition where a reply comes as the RequestX() call
had timeout, a NATS_TIMEOUT error would be returned along with
the message. Callers may not attempt to destroy the reply message
if the request call error'ed.

[FIXED] Request APIs could return error and msg, causing leak.

---

README.md

Change references from master to main branch

---

src/nats.c
src/natsp.h
src/util.c

Fixed LGTM reports

---

src/js.c
src/nats.h
test/test.c

Prepares for new $JS.ACK subject layout.

[ADDED] Domain in jsMsgMetData

---

src/js.c
test/test.c

This would happen when pull requests would have filled the waiting
queue in the JetStream consumer and a 408 status was returned.

[FIXED] natsSubscription_Fetch() could return immediately with a timeout error

---

test/test.c

Silence a warning on macOS BigSur

---

src/js.c
src/jsm.c
src/nats.h
test/test.c

Namely: MaxRequestBatch, MaxRequestExpires and InactiveThreshold

[ADDED] JetStream: UpdateConsumer and new consumer config's options

---

src/nats.h

[FIXED] Documentation of jsSubOptions.Consumer

---

src/conn.c
src/conn.h
src/js.c
src/jsm.c
src/kv.c
src/nats.h
src/natsp.h
test/list.txt
test/test.c

KV updates

---

src/js.c
src/jsm.c
src/nats.h
src/status.h
src/util.c
src/util.h
test/list.txt
test/test.c

[ADDED] JetStream: Ability to get subjects list from stream info

---

src/CMakeLists.txt

```
-rw-r--r-- root/root      1341 2022-02-16 09:16 ./usr/lib/x86_64-linux-gnu/cmake/cnats/cnats-config-none.cmake
-rw-r--r-- root/root      4356 2022-02-16 09:16 ./usr/lib/x86_64-linux-gnu/cmake/cnats/cnats-config.cmake
```

[FIXED] cmake files install path

---

src/js.c

If user does not specify MaxAckPending, don't set any value and
let the server pick the default.
Ensure that once we get the info back, we set the subscription
pending limits to at least cover this number.

[CHANGED] JetStream: do not set MaxAckPending if not user specified

---

src/js.c
src/jsm.c
src/nats.h
test/test.c

Revert some changes made to ordered consumer

---

README.md

Add an "Install" section in the README.md listing the known package managers.
Resolves #533
[ci skip]

[ADDED] List of known package managers

---

src/js.h
src/jsm.c

Makes use of the new subject and no payload for this request.

Update js_DirectGetMsg for "last by subject" cases

---

src/jsm.c
test/list.txt
test/test.c

Remove stream name check in "direct get" message API

---

src/conn.c
src/js.c
src/js.h
src/jsm.c
src/msg.c
src/msg.h
src/nats.h
src/natsp.h
test/test.c

Similar to natsSubscription_Fetch but allows user to fully configure the fetch request.

[ADDED] JetStream: natsSubscription_FetchRequest

---

src/js.h
src/jsm.c
src/nats.h
test/test.c

Two new APIs:
- `js_Consumers()` to get the list of consumers infos
- `js_ConsumerNames()` to get the list of consumer names

[ADDED] JetStream: Consumers list/names

---

src/js.c

Clone consumer config prior to call AddConsumer on ordred cons recreate

---

test/test.c

Since 2.9.4 sends a "409 Server Shutdown" on shutdown for r1 pull consumers, I am tweaking a test to drop HB messages instead of stopping the server to detect missing heartbeats.

Fixed test for server v2.9.4

---

MAINTAINERS.md

@gcolliso I am not sure this is the right process, but I noticed omission this morning, please LMK!

[CHANGED] Updated maintainers.md

---

dependencies.md

There was small mistake in table formating
Signed-off-by: Jarema <melgaer@gmail.com>

Fix dependencies formatting

---

.github/workflows/update-docs.yml

Fixes problems found in https://github.com/nats-io/nats.c/pull/722

[FIXED] doxygen GH action skip ci, include release_*

---

README.md

Updated to point at https://github.com/nats-io/nats.c/releases/tag/v3.8.2

Updated README.md for v3.8.2

---

CMakeLists.txt
README.md
doc/DoxyFile.NATS.Client
src/version.h

Update version to v3.12.0-beta [ci skip]
